name: twitter-sentiment-env
channels:
  - conda-forge

dependencies:
  # ── core ───────────────────────────────────────────
  - python=3.11
  - pip
  - jupyterlab
  - pandas
  - scikit-learn
  - optuna 
  - sqlalchemy

  # ── NLP / classical modeling ───────────────────────
  - spacy
  - nltk
  - fastapi
  - uvicorn
  - optuna                 # hyper‑parameter search
  - evaluate>=0.4          # quick metrics
  - yellowbrick            # visual diagnostics

  # ── ML / deep learning ─────────────────────────────
  - pytorch::pytorch-cuda=11.7   # GPU build with CUDA 11.7
  - torchvision
  - torchaudio
  - transformers>=4.41
  - datasets>=2.19
  - accelerate

  # ── lint / test / QA ───────────────────────────────
  - black
  - ruff
  - pre-commit
  - pytest
  - pytest-cov            # coverage reports

  # ── utilities ──────────────────────────────────────
  - joblib                # save / load sklearn models
  - shap                  # explainability

  # Everything below can be installed from PyPI if Conda is missing it
  - pip:
      - kaggle
