name: twitter-sentiment-env
channels:
  - conda-forge

dependencies:
  # ── core ────────────────────────────────────────────────
  - python=3.11
  - pip
  - jupyterlab
  - pandas
  - scikit-learn
  - numpy
  - matplotlib
  - seaborn

  # ── NLP / modeling ──────────────────────────────────────
  - spacy
  - nltk
  - fastapi
  - uvicorn
  - optuna
  - evaluate>=0.4              # quick metrics
  - yellowbrick                # visual diagnostics

  # ── ML / deep learning ─────────────────────────────────
  - pytorch::pytorch-cuda=11.7 
  - torchvision
  - torchaudio

  - transformers>=4.41
  - datasets>=2.19
  - accelerate

  # ── lint / test / qa ────────────────────────────────────
  - black
  - ruff
  - pre-commit
  - pytest
  - pytest-cov

  # ── utilities ──────────────────────────────────────────
  - joblib                     # save / load sklearn models
  - pip:
      - kaggle                 # if you download from Kaggle
