name: twitter-sentiment-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - pandas
  - scikit-learn
  - evaluate>=0.4  
  - nltk
  - spacy
  - tensorflow-cpu    
  - optuna
  - matplotlib
  - seaborn
  - fastapi
  - uvicorn
  - black
  - ruff
  - pre-commit
  - pytest
  - pyarrow  
  - joblib          # save / load fitted models
  - yellowbrick     # quick visual diagnostics
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.7   
  - pip
  - transformers>=4.41
  - datasets>=2.19
  - pytorch  
  - pip:
    - kaggle
    - torch       
    - torchvision
    - torchaudio
    - transformers
    - datasets
    - accelerate
