{
  "hash": "bbd529fb2fd150a308a95f127c487bcc",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: '**Baseline Classical Models**'\n---\n\n\n***\nEstablish a reproducible **TF‑IDF + Logistic Regression** benchmark for Twitter‑airline sentiment.\n\n* **Text column** → `clean_text`  \n* **Target label** → `airline_sentiment` (`negative`, `neutral`, `positive`)  \n* Train / validation / test = 70 / 15 / 15 (stratified)  \n* Persist artefacts to `models/`\n\n## Notebook Outline \n1. [Load Processed Data & Train-Test Split](#1-load-processed-data--train-test-split)  \n2. [Majority-class reference](#2-majority-class-reference)  \n3. [TF-IDF + Logistic Regression pipeline](#3-tf-idf--logistic-regression-pipeline)  \n4. [Validation performance](#4-validation-performance)  \n5. [5-fold stratified CV on *all* data](#5-5-fold-stratified-cv-on-all-data)  \n6. [Persisted Artifacts](#6-persisted-artifacts)  \n7. [Key Takeaway](#7-key-takeaway)\n\n\n::: {#81151a7e .cell execution_count=1}\n``` {.python .cell-code}\n# Imports\n# -------------------------------------------------------------------\nfrom __future__ import annotations\n\nimport json\nfrom pathlib import Path\n\nimport joblib\nimport pandas as pd\nfrom sklearn.model_selection import (\n    train_test_split,\n    cross_val_score,\n    StratifiedKFold,\n)\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.feature_extraction.text import TfidfVectorizer\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import (\n    classification_report,\n    ConfusionMatrixDisplay,\n)\n\n# -------------------------------------------------------------------\n# 1. Detect project root (folder that contains \"data/\")\nROOT_DIR = Path.cwd().parent  \n\n# 2. Define core directories\nDATA_DIR      = ROOT_DIR / \"data\"\nPROC_DATA_DIR = DATA_DIR / \"processed\"\nMODELS_DIR    = ROOT_DIR / \"models\"\nREPORT_DIR    = ROOT_DIR / \"reports\" / \"figs_04\"\n\nMODELS_DIR.mkdir(exist_ok=True)\nREPORT_DIR.mkdir(parents=True, exist_ok=True)\n\n# 3. Locate tweets.parquet (processed > raw fallback)\nPARQUET_PATH = (\n    PROC_DATA_DIR / \"tweets.parquet\"\n    if (PROC_DATA_DIR / \"tweets.parquet\").exists()\n    else DATA_DIR / \"tweets.parquet\"\n)\nassert PARQUET_PATH.exists(), f\"Missing parquet at {PARQUET_PATH}\"\n\n# 4. Log for sanity\nprint(f\"Project root  : {ROOT_DIR}\")\nprint(f\"Parquet source : {PARQUET_PATH.relative_to(ROOT_DIR)}\")\n\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nProject root  : C:\\Projects\\twitter-airline-analysis\nParquet source : data\\processed\\tweets.parquet\n```\n:::\n:::\n\n\n# 1.  Load Processed Data & Train-Test Split\n***\nWe keep raw string labels (`airline_sentiment`); scikit-learn encodes them internally.\n\n::: {#e973f61a .cell execution_count=2}\n``` {.python .cell-code}\nprint(Path.cwd())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nC:\\Projects\\twitter-airline-analysis\\notebooks\n```\n:::\n:::\n\n\n::: {#a6a772ea .cell execution_count=3}\n``` {.python .cell-code}\n# %% 2 Load processed data and create stratified splits\n# -------------------------------------------------------------------\ndf = pd.read_parquet(PARQUET_PATH)\n\n# Assert expected columns are present\nrequired_cols = {\"clean_text\", \"airline_sentiment\"}\nmissing = required_cols - set(df.columns)\nassert not missing, f\"Missing columns: {missing}\"\n\n# Sanity: no nulls in features / target\nassert df.clean_text.isna().sum() == 0\nassert df.airline_sentiment.isna().sum() == 0\n\n# Train / valid / test = 70 / 15 / 15\nX_train, X_temp, y_train, y_temp = train_test_split(\n    df.clean_text,\n    df.airline_sentiment,\n    test_size=0.30,\n    stratify=df.airline_sentiment,\n    random_state=42,\n)\nX_valid, X_test, y_valid, y_test = train_test_split(\n    X_temp,\n    y_temp,\n    test_size=0.50,\n    stratify=y_temp,\n    random_state=42,\n)\n\nprint(\n    f\"Splits → train:{len(X_train)}  valid:{len(X_valid)}  test:{len(X_test)}\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSplits → train:10248  valid:2196  test:2196\n```\n:::\n:::\n\n\n# 2.  Majority‑class reference\n***\n> **Majority‑class accuracy: 0.627**  \n> (Always predicting *negative* is correct 62.7 % of the time.)\n\n::: {#b60ab243 .cell execution_count=4}\n``` {.python .cell-code}\nmajority_acc = y_train.value_counts(normalize=True).max()\nprint(f\"Majority‑class accuracy: {majority_acc:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMajority‑class accuracy: 0.627\n```\n:::\n:::\n\n\n# 3. TF‑IDF + Logistic Regression pipeline\n***\nBi‑gram coverage, minimal regularisation tuning, and `class_weight='balanced'` to counter the 63 % negative skew.\n\n::: {#e18d0080 .cell execution_count=5}\n``` {.python .cell-code}\npipe_lr = Pipeline(\n    [\n        (\n            \"tfidf\",\n            TfidfVectorizer(\n                ngram_range=(1, 2),\n                min_df=2,\n                max_features=50_000,\n            ),\n        ),\n        (\n            \"clf\",\n            LogisticRegression(\n                max_iter=2_000,\n                n_jobs=-1,\n                class_weight=\"balanced\",\n            ),\n        ),\n    ]\n)\n\npipe_lr.fit(X_train, y_train)\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<style>#sk-container-id-1 {\n  /* Definition of color scheme common for light and dark mode */\n  --sklearn-color-text: #000;\n  --sklearn-color-text-muted: #666;\n  --sklearn-color-line: gray;\n  /* Definition of color scheme for unfitted estimators */\n  --sklearn-color-unfitted-level-0: #fff5e6;\n  --sklearn-color-unfitted-level-1: #f6e4d2;\n  --sklearn-color-unfitted-level-2: #ffe0b3;\n  --sklearn-color-unfitted-level-3: chocolate;\n  /* Definition of color scheme for fitted estimators */\n  --sklearn-color-fitted-level-0: #f0f8ff;\n  --sklearn-color-fitted-level-1: #d4ebff;\n  --sklearn-color-fitted-level-2: #b3dbfd;\n  --sklearn-color-fitted-level-3: cornflowerblue;\n\n  /* Specific color for light theme */\n  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n  --sklearn-color-icon: #696969;\n\n  @media (prefers-color-scheme: dark) {\n    /* Redefinition of color scheme for dark theme */\n    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n    --sklearn-color-icon: #878787;\n  }\n}\n\n#sk-container-id-1 {\n  color: var(--sklearn-color-text);\n}\n\n#sk-container-id-1 pre {\n  padding: 0;\n}\n\n#sk-container-id-1 input.sk-hidden--visually {\n  border: 0;\n  clip: rect(1px 1px 1px 1px);\n  clip: rect(1px, 1px, 1px, 1px);\n  height: 1px;\n  margin: -1px;\n  overflow: hidden;\n  padding: 0;\n  position: absolute;\n  width: 1px;\n}\n\n#sk-container-id-1 div.sk-dashed-wrapped {\n  border: 1px dashed var(--sklearn-color-line);\n  margin: 0 0.4em 0.5em 0.4em;\n  box-sizing: border-box;\n  padding-bottom: 0.4em;\n  background-color: var(--sklearn-color-background);\n}\n\n#sk-container-id-1 div.sk-container {\n  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n     but bootstrap.min.css set `[hidden] { display: none !important; }`\n     so we also need the `!important` here to be able to override the\n     default hidden behavior on the sphinx rendered scikit-learn.org.\n     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n  display: inline-block !important;\n  position: relative;\n}\n\n#sk-container-id-1 div.sk-text-repr-fallback {\n  display: none;\n}\n\ndiv.sk-parallel-item,\ndiv.sk-serial,\ndiv.sk-item {\n  /* draw centered vertical line to link estimators */\n  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n  background-size: 2px 100%;\n  background-repeat: no-repeat;\n  background-position: center center;\n}\n\n/* Parallel-specific style estimator block */\n\n#sk-container-id-1 div.sk-parallel-item::after {\n  content: \"\";\n  width: 100%;\n  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n  flex-grow: 1;\n}\n\n#sk-container-id-1 div.sk-parallel {\n  display: flex;\n  align-items: stretch;\n  justify-content: center;\n  background-color: var(--sklearn-color-background);\n  position: relative;\n}\n\n#sk-container-id-1 div.sk-parallel-item {\n  display: flex;\n  flex-direction: column;\n}\n\n#sk-container-id-1 div.sk-parallel-item:first-child::after {\n  align-self: flex-end;\n  width: 50%;\n}\n\n#sk-container-id-1 div.sk-parallel-item:last-child::after {\n  align-self: flex-start;\n  width: 50%;\n}\n\n#sk-container-id-1 div.sk-parallel-item:only-child::after {\n  width: 0;\n}\n\n/* Serial-specific style estimator block */\n\n#sk-container-id-1 div.sk-serial {\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  background-color: var(--sklearn-color-background);\n  padding-right: 1em;\n  padding-left: 1em;\n}\n\n\n/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\nclickable and can be expanded/collapsed.\n- Pipeline and ColumnTransformer use this feature and define the default style\n- Estimators will overwrite some part of the style using the `sk-estimator` class\n*/\n\n/* Pipeline and ColumnTransformer style (default) */\n\n#sk-container-id-1 div.sk-toggleable {\n  /* Default theme specific background. It is overwritten whether we have a\n  specific estimator or a Pipeline/ColumnTransformer */\n  background-color: var(--sklearn-color-background);\n}\n\n/* Toggleable label */\n#sk-container-id-1 label.sk-toggleable__label {\n  cursor: pointer;\n  display: flex;\n  width: 100%;\n  margin-bottom: 0;\n  padding: 0.5em;\n  box-sizing: border-box;\n  text-align: center;\n  align-items: start;\n  justify-content: space-between;\n  gap: 0.5em;\n}\n\n#sk-container-id-1 label.sk-toggleable__label .caption {\n  font-size: 0.6rem;\n  font-weight: lighter;\n  color: var(--sklearn-color-text-muted);\n}\n\n#sk-container-id-1 label.sk-toggleable__label-arrow:before {\n  /* Arrow on the left of the label */\n  content: \"▸\";\n  float: left;\n  margin-right: 0.25em;\n  color: var(--sklearn-color-icon);\n}\n\n#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {\n  color: var(--sklearn-color-text);\n}\n\n/* Toggleable content - dropdown */\n\n#sk-container-id-1 div.sk-toggleable__content {\n  display: none;\n  text-align: left;\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-1 div.sk-toggleable__content.fitted {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n#sk-container-id-1 div.sk-toggleable__content pre {\n  margin: 0.2em;\n  border-radius: 0.25em;\n  color: var(--sklearn-color-text);\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-1 div.sk-toggleable__content.fitted pre {\n  /* unfitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n  /* Expand drop-down */\n  display: block;\n  width: 100%;\n  overflow: visible;\n}\n\n#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n  content: \"▾\";\n}\n\n/* Pipeline/ColumnTransformer-specific style */\n\n#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Estimator-specific style */\n\n/* Colorize estimator box */\n#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n#sk-container-id-1 div.sk-label label.sk-toggleable__label,\n#sk-container-id-1 div.sk-label label {\n  /* The background is the default theme color */\n  color: var(--sklearn-color-text-on-default-background);\n}\n\n/* On hover, darken the color of the background */\n#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n/* Label box, darken color on hover, fitted */\n#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Estimator label */\n\n#sk-container-id-1 div.sk-label label {\n  font-family: monospace;\n  font-weight: bold;\n  display: inline-block;\n  line-height: 1.2em;\n}\n\n#sk-container-id-1 div.sk-label-container {\n  text-align: center;\n}\n\n/* Estimator-specific */\n#sk-container-id-1 div.sk-estimator {\n  font-family: monospace;\n  border: 1px dotted var(--sklearn-color-border-box);\n  border-radius: 0.25em;\n  box-sizing: border-box;\n  margin-bottom: 0.5em;\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-1 div.sk-estimator.fitted {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n/* on hover */\n#sk-container-id-1 div.sk-estimator:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-1 div.sk-estimator.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Specification for estimator info (e.g. \"i\" and \"?\") */\n\n/* Common style for \"i\" and \"?\" */\n\n.sk-estimator-doc-link,\na:link.sk-estimator-doc-link,\na:visited.sk-estimator-doc-link {\n  float: right;\n  font-size: smaller;\n  line-height: 1em;\n  font-family: monospace;\n  background-color: var(--sklearn-color-background);\n  border-radius: 1em;\n  height: 1em;\n  width: 1em;\n  text-decoration: none !important;\n  margin-left: 0.5em;\n  text-align: center;\n  /* unfitted */\n  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n  color: var(--sklearn-color-unfitted-level-1);\n}\n\n.sk-estimator-doc-link.fitted,\na:link.sk-estimator-doc-link.fitted,\na:visited.sk-estimator-doc-link.fitted {\n  /* fitted */\n  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n  color: var(--sklearn-color-fitted-level-1);\n}\n\n/* On hover */\ndiv.sk-estimator:hover .sk-estimator-doc-link:hover,\n.sk-estimator-doc-link:hover,\ndiv.sk-label-container:hover .sk-estimator-doc-link:hover,\n.sk-estimator-doc-link:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\ndiv.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n.sk-estimator-doc-link.fitted:hover,\ndiv.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n.sk-estimator-doc-link.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\n/* Span, style for the box shown on hovering the info icon */\n.sk-estimator-doc-link span {\n  display: none;\n  z-index: 9999;\n  position: relative;\n  font-weight: normal;\n  right: .2ex;\n  padding: .5ex;\n  margin: .5ex;\n  width: min-content;\n  min-width: 20ex;\n  max-width: 50ex;\n  color: var(--sklearn-color-text);\n  box-shadow: 2pt 2pt 4pt #999;\n  /* unfitted */\n  background: var(--sklearn-color-unfitted-level-0);\n  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n}\n\n.sk-estimator-doc-link.fitted span {\n  /* fitted */\n  background: var(--sklearn-color-fitted-level-0);\n  border: var(--sklearn-color-fitted-level-3);\n}\n\n.sk-estimator-doc-link:hover span {\n  display: block;\n}\n\n/* \"?\"-specific style due to the `<a>` HTML tag */\n\n#sk-container-id-1 a.estimator_doc_link {\n  float: right;\n  font-size: 1rem;\n  line-height: 1em;\n  font-family: monospace;\n  background-color: var(--sklearn-color-background);\n  border-radius: 1rem;\n  height: 1rem;\n  width: 1rem;\n  text-decoration: none;\n  /* unfitted */\n  color: var(--sklearn-color-unfitted-level-1);\n  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n}\n\n#sk-container-id-1 a.estimator_doc_link.fitted {\n  /* fitted */\n  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n  color: var(--sklearn-color-fitted-level-1);\n}\n\n/* On hover */\n#sk-container-id-1 a.estimator_doc_link:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\n#sk-container-id-1 a.estimator_doc_link.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-3);\n}\n\n.estimator-table summary {\n    padding: .5rem;\n    font-family: monospace;\n    cursor: pointer;\n}\n\n.estimator-table details[open] {\n    padding-left: 0.1rem;\n    padding-right: 0.1rem;\n    padding-bottom: 0.3rem;\n}\n\n.estimator-table .parameters-table {\n    margin-left: auto !important;\n    margin-right: auto !important;\n}\n\n.estimator-table .parameters-table tr:nth-child(odd) {\n    background-color: #fff;\n}\n\n.estimator-table .parameters-table tr:nth-child(even) {\n    background-color: #f6f6f6;\n}\n\n.estimator-table .parameters-table tr:hover {\n    background-color: #e0e0e0;\n}\n\n.estimator-table table td {\n    border: 1px solid rgba(106, 105, 104, 0.232);\n}\n\n.user-set td {\n    color:rgb(255, 94, 0);\n    text-align: left;\n}\n\n.user-set td.value pre {\n    color:rgb(255, 94, 0) !important;\n    background-color: transparent !important;\n}\n\n.default td {\n    color: black;\n    text-align: left;\n}\n\n.user-set td i,\n.default td i {\n    color: black;\n}\n\n.copy-paste-icon {\n    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tIUZvbnQgQXdlc29tZSBGcmVlIDYuNy4yIGJ5IEBmb250YXdlc29tZSAtIGh0dHBzOi8vZm9udGF3ZXNvbWUuY29tIExpY2Vuc2UgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbS9saWNlbnNlL2ZyZWUgQ29weXJpZ2h0IDIwMjUgRm9udGljb25zLCBJbmMuLS0+PHBhdGggZD0iTTIwOCAwTDMzMi4xIDBjMTIuNyAwIDI0LjkgNS4xIDMzLjkgMTQuMWw2Ny45IDY3LjljOSA5IDE0LjEgMjEuMiAxNC4xIDMzLjlMNDQ4IDMzNmMwIDI2LjUtMjEuNSA0OC00OCA0OGwtMTkyIDBjLTI2LjUgMC00OC0yMS41LTQ4LTQ4bDAtMjg4YzAtMjYuNSAyMS41LTQ4IDQ4LTQ4ek00OCAxMjhsODAgMCAwIDY0LTY0IDAgMCAyNTYgMTkyIDAgMC0zMiA2NCAwIDAgNDhjMCAyNi41LTIxLjUgNDgtNDggNDhMNDggNTEyYy0yNi41IDAtNDgtMjEuNS00OC00OEwwIDE3NmMwLTI2LjUgMjEuNS00OCA0OC00OHoiLz48L3N2Zz4=);\n    background-repeat: no-repeat;\n    background-size: 14px 14px;\n    background-position: 0;\n    display: inline-block;\n    width: 14px;\n    height: 14px;\n    cursor: pointer;\n}\n</style><body><div id=\"sk-container-id-1\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>Pipeline(steps=[(&#x27;tfidf&#x27;,\n                 TfidfVectorizer(max_features=50000, min_df=2,\n                                 ngram_range=(1, 2))),\n                (&#x27;clf&#x27;,\n                 LogisticRegression(class_weight=&#x27;balanced&#x27;, max_iter=2000,\n                                    n_jobs=-1))])</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item sk-dashed-wrapped\"><div class=\"sk-label-container\"><div class=\"sk-label fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-1\" type=\"checkbox\" ><label for=\"sk-estimator-id-1\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>Pipeline</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.7/modules/generated/sklearn.pipeline.Pipeline.html\">?<span>Documentation for Pipeline</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\" data-param-prefix=\"\">\n        <div class=\"estimator-table\">\n            <details>\n                <summary>Parameters</summary>\n                <table class=\"parameters-table\">\n                  <tbody>\n                    \n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('steps',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">steps&nbsp;</td>\n            <td class=\"value\">[(&#x27;tfidf&#x27;, ...), (&#x27;clf&#x27;, ...)]</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('transform_input',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">transform_input&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('memory',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">memory&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('verbose',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">verbose&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n                  </tbody>\n                </table>\n            </details>\n        </div>\n    </div></div></div><div class=\"sk-serial\"><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-2\" type=\"checkbox\" ><label for=\"sk-estimator-id-2\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>TfidfVectorizer</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.7/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html\">?<span>Documentation for TfidfVectorizer</span></a></div></label><div class=\"sk-toggleable__content fitted\" data-param-prefix=\"tfidf__\">\n        <div class=\"estimator-table\">\n            <details>\n                <summary>Parameters</summary>\n                <table class=\"parameters-table\">\n                  <tbody>\n                    \n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('input',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">input&nbsp;</td>\n            <td class=\"value\">&#x27;content&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('encoding',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">encoding&nbsp;</td>\n            <td class=\"value\">&#x27;utf-8&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('decode_error',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">decode_error&nbsp;</td>\n            <td class=\"value\">&#x27;strict&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('strip_accents',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">strip_accents&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('lowercase',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">lowercase&nbsp;</td>\n            <td class=\"value\">True</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('preprocessor',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">preprocessor&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('tokenizer',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">tokenizer&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('analyzer',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">analyzer&nbsp;</td>\n            <td class=\"value\">&#x27;word&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('stop_words',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">stop_words&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('token_pattern',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">token_pattern&nbsp;</td>\n            <td class=\"value\">&#x27;(?u)\\\\b\\\\w\\\\w+\\\\b&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('ngram_range',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">ngram_range&nbsp;</td>\n            <td class=\"value\">(1, ...)</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('max_df',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">max_df&nbsp;</td>\n            <td class=\"value\">1.0</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('min_df',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">min_df&nbsp;</td>\n            <td class=\"value\">2</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('max_features',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">max_features&nbsp;</td>\n            <td class=\"value\">50000</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('vocabulary',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">vocabulary&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('binary',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">binary&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('dtype',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">dtype&nbsp;</td>\n            <td class=\"value\">&lt;class &#x27;numpy.float64&#x27;&gt;</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('norm',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">norm&nbsp;</td>\n            <td class=\"value\">&#x27;l2&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('use_idf',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">use_idf&nbsp;</td>\n            <td class=\"value\">True</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('smooth_idf',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">smooth_idf&nbsp;</td>\n            <td class=\"value\">True</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('sublinear_tf',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">sublinear_tf&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n                  </tbody>\n                </table>\n            </details>\n        </div>\n    </div></div></div><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-3\" type=\"checkbox\" ><label for=\"sk-estimator-id-3\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>LogisticRegression</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.7/modules/generated/sklearn.linear_model.LogisticRegression.html\">?<span>Documentation for LogisticRegression</span></a></div></label><div class=\"sk-toggleable__content fitted\" data-param-prefix=\"clf__\">\n        <div class=\"estimator-table\">\n            <details>\n                <summary>Parameters</summary>\n                <table class=\"parameters-table\">\n                  <tbody>\n                    \n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('penalty',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">penalty&nbsp;</td>\n            <td class=\"value\">&#x27;l2&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('dual',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">dual&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('tol',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">tol&nbsp;</td>\n            <td class=\"value\">0.0001</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('C',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">C&nbsp;</td>\n            <td class=\"value\">1.0</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('fit_intercept',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">fit_intercept&nbsp;</td>\n            <td class=\"value\">True</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('intercept_scaling',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">intercept_scaling&nbsp;</td>\n            <td class=\"value\">1</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('class_weight',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">class_weight&nbsp;</td>\n            <td class=\"value\">&#x27;balanced&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('random_state',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">random_state&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('solver',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">solver&nbsp;</td>\n            <td class=\"value\">&#x27;lbfgs&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('max_iter',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">max_iter&nbsp;</td>\n            <td class=\"value\">2000</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('multi_class',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">multi_class&nbsp;</td>\n            <td class=\"value\">&#x27;deprecated&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('verbose',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">verbose&nbsp;</td>\n            <td class=\"value\">0</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('warm_start',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">warm_start&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('n_jobs',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">n_jobs&nbsp;</td>\n            <td class=\"value\">-1</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('l1_ratio',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">l1_ratio&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n                  </tbody>\n                </table>\n            </details>\n        </div>\n    </div></div></div></div></div></div></div><script>function copyToClipboard(text, element) {\n    // Get the parameter prefix from the closest toggleable content\n    const toggleableContent = element.closest('.sk-toggleable__content');\n    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n    const fullParamName = paramPrefix ? `${paramPrefix}${text}` : text;\n\n    const originalStyle = element.style;\n    const computedStyle = window.getComputedStyle(element);\n    const originalWidth = computedStyle.width;\n    const originalHTML = element.innerHTML.replace('Copied!', '');\n\n    navigator.clipboard.writeText(fullParamName)\n        .then(() => {\n            element.style.width = originalWidth;\n            element.style.color = 'green';\n            element.innerHTML = \"Copied!\";\n\n            setTimeout(() => {\n                element.innerHTML = originalHTML;\n                element.style = originalStyle;\n            }, 2000);\n        })\n        .catch(err => {\n            console.error('Failed to copy:', err);\n            element.style.color = 'red';\n            element.innerHTML = \"Failed!\";\n            setTimeout(() => {\n                element.innerHTML = originalHTML;\n                element.style = originalStyle;\n            }, 2000);\n        });\n    return false;\n}\n\ndocument.querySelectorAll('.fa-regular.fa-copy').forEach(function(element) {\n    const toggleableContent = element.closest('.sk-toggleable__content');\n    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n    const paramName = element.parentElement.nextElementSibling.textContent.trim();\n    const fullParamName = paramPrefix ? `${paramPrefix}${paramName}` : paramName;\n\n    element.setAttribute('title', fullParamName);\n});\n</script></body>\n```\n:::\n:::\n\n\n# 4. Validation performance\n***\n\n| Metric | Score |\n| ------ | ----- |\n| **Accuracy** | **0.788** |\n| **Macro F1** | **0.741** |\n| Weighted F1 | 0.792 |\n\nThe model is strongest on the *negative* class (precision ≈ 0.89) and weakest on *neutral*—an expected pattern given the class imbalance.\n\n::: {#4adf0719 .cell execution_count=6}\n``` {.python .cell-code}\nprint(\n    classification_report(\n        y_valid,\n        pipe_lr.predict(X_valid),\n        digits=3,\n        target_names=[\"neg\", \"neu\", \"pos\"],\n    )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              precision    recall  f1-score   support\n\n         neg      0.888     0.836     0.862      1376\n         neu      0.590     0.703     0.642       465\n         pos      0.728     0.710     0.719       355\n\n    accuracy                          0.788      2196\n   macro avg      0.736     0.750     0.741      2196\nweighted avg      0.799     0.788     0.792      2196\n\n```\n:::\n:::\n\n\n# 5. 5‑fold stratified CV on *all* data\n***\n\n**Cross-Validated Macro F1:** **0.749 ± 0.007**\n\nThe low standard deviation indicates the baseline is stable across folds.\n\n::: {#c3fc2c1a .cell execution_count=7}\n``` {.python .cell-code}\ncv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n\ncv_scores = cross_val_score(\n    pipe_lr,\n    df.clean_text,\n    df.airline_sentiment,\n    cv=cv,\n    scoring=\"f1_macro\",\n    n_jobs=-1,\n)\n\nprint(f\"CV F1_macro = {cv_scores.mean():.3f} ± {cv_scores.std():.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCV F1_macro = 0.749 ± 0.007\n```\n:::\n:::\n\n\n## Held-Out Test Set Confusion Matrix\n\nThe confusion matrix visually confirms the model's strengths and areas for improvement:\n\n- **Negative Class:** Excellent recall and precision.\n- **Neutral Class:** Frequent confusion with both *negative* and *positive* classes indicates difficulty capturing neutrality.\n\n*(Matrix figure saved as `reports/figs_04/conf_matrix.png`.)*\n\n::: {#8d21c93b .cell execution_count=8}\n``` {.python .cell-code}\n# %% 7 │ Test‑set metrics table  ──────────────────────────────────────────────\nimport pandas as pd\nfrom sklearn.metrics import classification_report, accuracy_score, f1_score\nimport matplotlib.pyplot as plt\n\n# %% 6 │ Held‑out predictions  -----------------------------------------------\ny_pred = pipe_lr.predict(X_test)   # X_test comes from the earlier split cell\n\n# y_test, y_pred assumed from previous cell\nreport_dict = classification_report(\n    y_test, y_pred,\n    target_names=[\"negative\", \"neutral\", \"positive\"],\n    output_dict=True,\n    zero_division=0           # avoid warnings if any class missing\n)\n\n# tidy DataFrame, keep only precision/recall/f1\nmetrics_df = (\n    pd.DataFrame(report_dict)\n      .T                                   # classes as rows\n      .loc[[\"negative\", \"neutral\", \"positive\", \"weighted avg\"],  # row order\n           [\"precision\", \"recall\", \"f1-score\"]]\n      .rename(index={\"weighted avg\": \"weighted\"})                # shorter name\n      .round(3)\n)\n\ndisplay(metrics_df)\n\n# quick one‑liner with global accuracy & weighted‑F1\noverall = pd.Series({\n    \"accuracy\":      accuracy_score(y_test, y_pred),\n    \"weighted‑F1\":   f1_score(y_test, y_pred, average=\"weighted\")\n}).round(3)\n\nprint(\"\\nOverall:\", overall.to_dict())\n\ndisp = ConfusionMatrixDisplay.from_predictions(\n    y_test, y_pred,\n    labels=[\"negative\", \"neutral\", \"positive\"],\n    cmap=\"YlGnBu\", xticks_rotation=45, colorbar=True\n)\n\nplt.title(\"Held‑out test‑set confusion matrix\")\nplt.tight_layout()\nplt.savefig(REPORT_DIR / \"conf_matrix.png\", dpi=150)\nplt.show()                     # ← forces render in notebook\n\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>precision</th>\n      <th>recall</th>\n      <th>f1-score</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>negative</th>\n      <td>0.889</td>\n      <td>0.840</td>\n      <td>0.864</td>\n    </tr>\n    <tr>\n      <th>neutral</th>\n      <td>0.595</td>\n      <td>0.686</td>\n      <td>0.637</td>\n    </tr>\n    <tr>\n      <th>positive</th>\n      <td>0.709</td>\n      <td>0.718</td>\n      <td>0.713</td>\n    </tr>\n    <tr>\n      <th>weighted</th>\n      <td>0.798</td>\n      <td>0.788</td>\n      <td>0.792</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nOverall: {'accuracy': 0.788, 'weighted‑F1': 0.792}\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](04_baseline_model_files/figure-html/cell-9-output-3.png){width=547 height=468}\n:::\n:::\n\n\n# 6. Persisted Artifacts\n***\n\n- **Model:** `models/logreg_tfidf.joblib`  \n- **Cross-Validation Scores:** `models/cv_logreg.json`\n\n::: {#77d1a8c0 .cell execution_count=9}\n``` {.python .cell-code}\nMODEL_PATH = MODELS_DIR / \"logreg_tfidf.joblib\"\nCV_PATH    = MODELS_DIR / \"cv_logreg.json\"\n\njoblib.dump(pipe_lr, MODEL_PATH)\nprint(f\"Saved model → {MODEL_PATH.relative_to(ROOT_DIR)}\")\n\nwith CV_PATH.open(\"w\") as fp:\n    json.dump({\"f1_macro\": cv_scores.tolist()}, fp, indent=2)\nprint(f\"Saved CV scores → {CV_PATH.relative_to(ROOT_DIR)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSaved model → models\\logreg_tfidf.joblib\nSaved CV scores → models\\cv_logreg.json\n```\n:::\n:::\n\n\n# 7. Key Takeaway\n***\n\n* Baseline (majority class) caps out at **62.7 %** accuracy.  \n* TF‑IDF + Logistic Regression lifts validation accuracy to **78.8 %** and macro F1 to **0.74**.  \n* 5‑fold CV confirms robustness (**0.749 ± 0.007** macro F1).  \n* Confusion matrix shows excellent precision for the *negative* class but persistent confusion between *neutral* and both extremes.  \n* With class‑weight balancing and bigram coverage, a classical model already delivers a **+16 pp accuracy gain** over the baseline—good enough for a production fallback while we prototype transformer models in Milestone 5.\n\n",
    "supporting": [
      "04_baseline_model_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}