{
  "hash": "aa7d68d085ba32e2a1a8953feded8398",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: '**Project Overview**'\n---\n\n\n---\n\nThis notebook provides an initial examination of the **Twitter US Airline Sentiment** dataset (≈ 14 600 tweets, February 2015) and generates two baseline visualizations that will inform subsequent data‑preparation and modeling work.\n\n\n## Objectives\n\n1. Load the raw CSV file into a pandas DataFrame.  \n2. Summarize overall sentiment distribution.  \n3. Compare sentiment across individual airlines.  \n4. Record key observations to guide the modeling plan.\n\n## Notebook Outline \n1. [Load Data](#1-load-data)  \n2. [Data Structure](#2-data-structure)  \n3. [Sentiment Distribution](#3-sentiment-distribution)  \n4. [Sentiment by Airline](#4-sentiment-by-airline)  \n5. [Key Observations](#5-key-observations)\n\n::: {#ef9cd605 .cell execution_count=1}\n``` {.python .cell-code}\n# core libraries\nfrom pathlib import Path\n\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\nPROJ_ROOT = Path.cwd().parent\nDATA_DIR  = PROJ_ROOT / \"data\" / \"raw\"\nCSV_PATH = DATA_DIR / \"Tweets.csv\"\nFIG_DIR   = PROJ_ROOT / \"reports\" / \"figs_eda\"\nFIG_DIR.mkdir(parents=True, exist_ok=True)\n```\n:::\n\n\n# 1. Load Data\n***\n\n::: {#867a5fe0 .cell execution_count=2}\n``` {.python .cell-code}\ndf = pd.read_csv(CSV_PATH)\ndisplay(df.head())\nprint(df.shape)\ndf.info(show_counts=True)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>tweet_id</th>\n      <th>airline_sentiment</th>\n      <th>airline_sentiment_confidence</th>\n      <th>negativereason</th>\n      <th>negativereason_confidence</th>\n      <th>airline</th>\n      <th>airline_sentiment_gold</th>\n      <th>name</th>\n      <th>negativereason_gold</th>\n      <th>retweet_count</th>\n      <th>text</th>\n      <th>tweet_coord</th>\n      <th>tweet_created</th>\n      <th>tweet_location</th>\n      <th>user_timezone</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>570306133677760513</td>\n      <td>neutral</td>\n      <td>1.0000</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Virgin America</td>\n      <td>NaN</td>\n      <td>cairdin</td>\n      <td>NaN</td>\n      <td>0</td>\n      <td>@VirginAmerica What @dhepburn said.</td>\n      <td>NaN</td>\n      <td>2015-02-24 11:35:52 -0800</td>\n      <td>NaN</td>\n      <td>Eastern Time (US &amp; Canada)</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>570301130888122368</td>\n      <td>positive</td>\n      <td>0.3486</td>\n      <td>NaN</td>\n      <td>0.0000</td>\n      <td>Virgin America</td>\n      <td>NaN</td>\n      <td>jnardino</td>\n      <td>NaN</td>\n      <td>0</td>\n      <td>@VirginAmerica plus you've added commercials t...</td>\n      <td>NaN</td>\n      <td>2015-02-24 11:15:59 -0800</td>\n      <td>NaN</td>\n      <td>Pacific Time (US &amp; Canada)</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>570301083672813571</td>\n      <td>neutral</td>\n      <td>0.6837</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Virgin America</td>\n      <td>NaN</td>\n      <td>yvonnalynn</td>\n      <td>NaN</td>\n      <td>0</td>\n      <td>@VirginAmerica I didn't today... Must mean I n...</td>\n      <td>NaN</td>\n      <td>2015-02-24 11:15:48 -0800</td>\n      <td>Lets Play</td>\n      <td>Central Time (US &amp; Canada)</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>570301031407624196</td>\n      <td>negative</td>\n      <td>1.0000</td>\n      <td>Bad Flight</td>\n      <td>0.7033</td>\n      <td>Virgin America</td>\n      <td>NaN</td>\n      <td>jnardino</td>\n      <td>NaN</td>\n      <td>0</td>\n      <td>@VirginAmerica it's really aggressive to blast...</td>\n      <td>NaN</td>\n      <td>2015-02-24 11:15:36 -0800</td>\n      <td>NaN</td>\n      <td>Pacific Time (US &amp; Canada)</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>570300817074462722</td>\n      <td>negative</td>\n      <td>1.0000</td>\n      <td>Can't Tell</td>\n      <td>1.0000</td>\n      <td>Virgin America</td>\n      <td>NaN</td>\n      <td>jnardino</td>\n      <td>NaN</td>\n      <td>0</td>\n      <td>@VirginAmerica and it's a really big bad thing...</td>\n      <td>NaN</td>\n      <td>2015-02-24 11:14:45 -0800</td>\n      <td>NaN</td>\n      <td>Pacific Time (US &amp; Canada)</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n(14640, 15)\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 14640 entries, 0 to 14639\nData columns (total 15 columns):\n #   Column                        Non-Null Count  Dtype  \n---  ------                        --------------  -----  \n 0   tweet_id                      14640 non-null  int64  \n 1   airline_sentiment             14640 non-null  object \n 2   airline_sentiment_confidence  14640 non-null  float64\n 3   negativereason                9178 non-null   object \n 4   negativereason_confidence     10522 non-null  float64\n 5   airline                       14640 non-null  object \n 6   airline_sentiment_gold        40 non-null     object \n 7   name                          14640 non-null  object \n 8   negativereason_gold           32 non-null     object \n 9   retweet_count                 14640 non-null  int64  \n 10  text                          14640 non-null  object \n 11  tweet_coord                   1019 non-null   object \n 12  tweet_created                 14640 non-null  object \n 13  tweet_location                9907 non-null   object \n 14  user_timezone                 9820 non-null   object \ndtypes: float64(2), int64(2), object(11)\nmemory usage: 1.7+ MB\n```\n:::\n:::\n\n\n# 2. Data Structure\n***\n\n| Column                       | Dtype   | Description                                                 |\n|------------------------------|---------|-------------------------------------------------------------|\n| `tweet_id`                   | int64   | Unique tweet identifier                                     |\n| `airline_sentiment`          | object  | Labeled sentiment (`negative`, `neutral`, `positive`)       |\n| `airline_sentiment_confidence` | float64 | Model confidence for `airline_sentiment`                    |\n| `negativereason`             | object  | Reason for negative sentiment (NaN for neutral/positive)    |\n| `negativereason_confidence`  | float64 | Model confidence for `negativereason`                       |\n| `airline`                    | object  | Airline name (`American`, `Delta`, `United`, …)             |\n| `airline_sentiment_gold`     | object  | Gold‑standard label (very sparse)                           |\n| `name`                       | object  | Twitter handle of the author                                |\n| `negativereason_gold`        | object  | Gold‑standard negative reason (very sparse)                 |\n| `retweet_count`              | int64   | How many times the tweet was retweeted                      |\n| `text`                       | object  | Full tweet text                                             |\n| `tweet_coord`                | object  | GPS coordinates if provided                                 |\n| `tweet_created`              | object  | UTC timestamp string                                        |\n| `tweet_location`             | object  | User‑provided location                                      |\n| `user_timezone`              | object  | User‐reported timezone                                      |\n\n# 3. Sentiment Distribution\n***\n\nThe bar chart below illustrates the overall class balance (9 178 negative, 3 099 neutral, 2 363 positive).  \nThe figure is saved to **`reports/fig_sentiment_distribution.png`**.\n\n| Sentiment | Tweets | Share |\n|-----------|--------|-------|\n| Negative  | 9 178  | 62.7 % |\n| Neutral   | 3 099  | 21.2 % |\n| Positive  | 2 363  | 16.1 % |\n\n::: {#76b2de3f .cell execution_count=3}\n``` {.python .cell-code}\nsent_counts = df[\"airline_sentiment\"].value_counts().sort_index()\n\nplt.figure(figsize=(6, 4))                # single plot\nsns.barplot(x=sent_counts.index, y=sent_counts.values)\nplt.title(\"Overall sentiment distribution\")\nplt.ylabel(\"Tweet count\")\nplt.tight_layout()\nfig_path = FIG_DIR / \"fig_sentiment_distribution.png\"\nplt.savefig(fig_path, dpi=150, bbox_inches=\"tight\")\n```\n\n::: {.cell-output .cell-output-display}\n![](01_project_overview_files/figure-html/cell-4-output-1.png){width=565 height=372}\n:::\n:::\n\n\n# 4. Sentiment by Airline\n***\n\nThe heatmap below shows sentiment counts for each airline.  \nThe figure is saved to **`reports/fig_sentiment_by_airline.png`**.\n\n| Airline          | Negative | Neutral | Positive |\n|------------------|---------:|--------:|---------:|\n| American         | 1 960 | 463 | 336 |\n| Delta            |   955 | 723 | 544 |\n| Southwest        | 1 186 | 664 | 570 |\n| US Airways       | 2 263 | 381 | 269 |\n| United           | 2 633 | 697 | 492 |\n| Virgin America   |   181 | 171 | 152 |\n\n::: {#ad15db55 .cell execution_count=4}\n``` {.python .cell-code}\npivot = (\n    df.pivot_table(\n        index=\"airline\", \n        columns=\"airline_sentiment\", \n        values=\"tweet_id\", \n        aggfunc=\"count\",\n        fill_value=0,\n    )\n    .loc[:, [\"negative\", \"neutral\", \"positive\"]]\n)\n\nplt.figure(figsize=(6, 3))\nsns.heatmap(pivot, annot=True, fmt=\"d\", cmap=\"YlGnBu\")\nplt.title(\"Sentiment by airline\")\nplt.tight_layout()\nfig_path2 = FIG_DIR / \"fig_sentiment_by_airline.png\"\nplt.savefig(fig_path2, dpi=150)\n```\n\n::: {.cell-output .cell-output-display}\n![](01_project_overview_files/figure-html/cell-5-output-1.png){width=555 height=276}\n:::\n:::\n\n\n# 5. Key Observations\n***\n\n- The dataset is **imbalanced**: 62.7 % negative, 21.2 % neutral, and 16.1 % positive.  \n  *Implication*: stratified splits and class weighting will be required to avoid biased models.  \n- **United** and **US Airways** receive the highest volumes of negative tweets (2 633 and 2 263 respectively).  \n- **American** also attracts many complaints, whereas **Southwest** shows a comparatively higher share of positive tweets.  \n- Text preprocessing must address URLs, mentions, casing, and lemmatization before vectorization.  \n- The `negativereason` column is populated for ~9 000 rows; it may enable multi‑task learning or error‑analysis later.\n\n",
    "supporting": [
      "01_project_overview_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}