name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pre-commit (if config present)
        if: ${{ hashFiles('.pre-commit-config.yaml') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit run --all-files --show-diff-on-failure

      - name: Build Docker image
        run: docker build -t airline-sentiment:${{ github.sha }} .

      - name: Log in to GHCR (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag airline-sentiment:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/airline-sentiment:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository_owner }}/airline-sentiment:${{ github.ref_name }}
